// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvDIc6iXLEUxKQj_8Y8In3yKXq58_cJEg',
    appId: '1:971982451447:web:a31f3910b9706d4534d9f2',
    messagingSenderId: '971982451447',
    projectId: 'sentrylens',
    authDomain: 'sentrylens.firebaseapp.com',
    storageBucket: 'sentrylens.firebasestorage.app',
    measurementId: 'G-H2D3YQ641S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHuCD-5BL7pCXyK2aQoeq79d_Nfo0aY0',
    appId: '1:971982451447:android:444858eae2507f7034d9f2',
    messagingSenderId: '971982451447',
    projectId: 'sentrylens',
    storageBucket: 'sentrylens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxG1Y4oNqGedDrrBiCZvlFP42GbDUShyg',
    appId: '1:971982451447:ios:4adbfd74d17f9dc834d9f2',
    messagingSenderId: '971982451447',
    projectId: 'sentrylens',
    storageBucket: 'sentrylens.firebasestorage.app',
    iosBundleId: 'com.example.sentryLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxG1Y4oNqGedDrrBiCZvlFP42GbDUShyg',
    appId: '1:971982451447:ios:4adbfd74d17f9dc834d9f2',
    messagingSenderId: '971982451447',
    projectId: 'sentrylens',
    storageBucket: 'sentrylens.firebasestorage.app',
    iosBundleId: 'com.example.sentryLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvDIc6iXLEUxKQj_8Y8In3yKXq58_cJEg',
    appId: '1:971982451447:web:f4dc5b000fe527e034d9f2',
    messagingSenderId: '971982451447',
    projectId: 'sentrylens',
    authDomain: 'sentrylens.firebaseapp.com',
    storageBucket: 'sentrylens.firebasestorage.app',
    measurementId: 'G-WH3JK0WD3M',
  );
}
